[supabase]
url = "https://kykmgubflghblstfnsdn.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5a21ndWJmbGdoYmxzdGZuc2RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNDA0MTEsImV4cCI6MjA4NjgxNjQxMX0.J8y5JRnm-rGDqNb83u6YTlf7Gunz6lRIg9v5VGBGgw4"
